config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#index"
  resources :homes do
    resources :comments
  end
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :home
  validates :name, length: { minimum: 1}
  validates :comment, length: { minimum: 1 }
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    byebug
    @login = !!User.find_by(id: session[:userId])
    @home = Home.find(params[:home_id])
    if @home.comments[0] != nil
      @comments = @home.comments.all
      @comment = @comments[0]
    else
      @comment = Comment.new
      @comments = nil
    end


    puts @home
  end

  def create

    @home = Home.find(params[:home_id])
    params["comment"]
    @home.comments.create({name: params["comment"]["name"] , comment: params["comment"]["comment"], url: params["comment"]["url"].split("=")[1]})

    redirect_to home_comments_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @home = Home.all
  end

  def show
    @home = Home.find(params[:id])
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(board_params)
    @home.save
    redirect_to @home
  end


  private

  def board_params
    params.require(:home).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    byebug
    @user = User.find_by(name: params["user"]["name"])
    if @user != nil
      if @user.authenticate(params["user"]["password"])
        session[:id] = @user.id
        redirect_to "/homes"
      else
        redirect_to "/login", notice: "login failed! Try Again"
      end
    else
      redirect_to "/login", notice: "login failed! Try Again" 
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create({name: params["user"]["name"], password: params["user"]["password"]})
    byebug
    session[:userId] = @user.id
    redirect_to "/homes"
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<%= render :partial => "layouts/header" %>

<% if @login %>
<div class="threadtitle">
  <%= @home.title %>
</div>
<hr />
<% if @comments != nil %>
  <ul>
  <% @comments.each do |comment| %>
  <li>
      <div>
      <div class="name">
      <div class="nameTag">
        name
      </div>
      <%= comment.name %>
      <%= comment.created_at.to_time %>
      </div>
      <div class="comment">
        <div class="commentTag">comment</div>
      <%= comment.comment %>
      </div>
      <div>
        <% if comment.url != nil %>
        <iframe width="560" height="315" src=<%= "https://www.youtube.com/embed/#{comment.url}" %> frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        <% end %>
      </div>
      </div>
  </li>
    <hr />
  <% end %>
  </ul>
<% end %>

  <%= form_for @comment, url: {action: "create"}, method: "post" ,html: {class: "nifty_form"} do |f| %>
    <label for="">name</label>
    <%= f.text_field :name, class:"nameinput" %>
    <label for="">Comment</label>
    <%= f.text_area :comment, class:"commentArea" %>
    <label for="">URL of YouTube</label>
    <%= f.text_field :url, class:"nameinput" %>
    <%= f.submit "Create" %>
  <% end %>
<% end %>

<% if !@login %>
  <p>Please login</p>
<% end %>

app/views/homes/index.html.erb
<%= render :partial => "header" %>

<div class="createNewThread">
<a class="newThread" href="/homes/new">create new thread</a>
</div>
<ul>
<% if @home != nil %>
<% @home.each do |home| %>
    <li>
      <div class="title">
      <%= link_to home.title, "#{home_path(home)}/comments" %>
      </div>
      <div class="description">
        <%= home.description %>
      </div>
    </li>
    <hr />
  <% end %>
<% end %>
</ul>

app/views/homes/new.html.erb
<%= render :partial => "header" %>


<%= form_for @home, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <label for="">Title</label>
  <%= f.text_field :title %>
  <label for="">Description</label>
  <%= f.text_area :description, size: "60x12" %>
  <%= f.submit "Create" %>
<% end %>

app/views/homes/show.html.erb
<%= render :partial => "header" %>

    <div class="container">
      <div class="innerContent">You created new thread!</div>
      <div class="innerContent">The title is  <%= @home.title %></div>
      <div class="innerContent">This desctription is <%= @home.description %></div>
      <a class="innerContent" href="/homes">GO BACK To List Of Thread</a>
    </div>

app/views/layouts/_header.html.erb
<div class="header">SoccerBoard</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoccerBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<h1>user index</h1>
<a href="/login">login</a>
<a href="/users/new">singup</a>

app/views/users/new.html.erb
<%= render :partial => "/layouts/header" %>

<%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.text_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.text_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>